# Generated by Django 5.2.17 on 2026-08-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_customer_event_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_style', models.CharField(choices=[('buffet', 'Buffet'), ('plated', 'Plated Service'), ('finger_foods', 'Cocktail / Finger Foods'), ('family_style', 'Family Style'), ('packed_meals', 'Packed Meals'), ('custom', 'Custom')], max_length=30)),
                ('number_of_servers', models.PositiveIntegerField(default=0)),
                ('setup_required', models.BooleanField(default=False)),
                ('cleanup_required', models.BooleanField(default=False)),
                ('tableware_required', models.BooleanField(default=False)),
                ('equipment_required', models.BooleanField(default=False)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('budget_range', models.CharField(choices=[('under_500', 'Under 500'), ('500_1000', '500 - 1,000'), ('1000_2500', '1,000 - 2,500'), ('2500_5000', '2,500 - 5,000'), ('5000_10000', '5,000 - 10,000'), ('over_10000', 'Over 10,000'), ('not_specified', 'Not Specified')], default='not_specified', max_length=30)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catering_requirement', to='events.event')),
            ],
            options={
                'verbose_name': 'Catering Requirement',
                'verbose_name_plural': 'Catering Requirements',
            },
        ),
    ]
