# Generated by Django 5.2.17 on 2026-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_quoteitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_style', models.CharField(choices=[('buffet', 'Buffet'), ('plated', 'Plated Dinner'), ('cocktail', 'Cocktail / Finger Foods'), ('breakfast', 'Breakfast / Brunch')], max_length=30, unique=True)),
                ('price_per_guest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_guests', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
