# Generated by Django 5.2.17 on 2026-08-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_servicepricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('service_style', models.CharField(choices=[('buffet', 'Buffet'), ('plated', 'Plated Dinner'), ('cocktail', 'Cocktail / Finger Foods'), ('breakfast', 'Breakfast / Brunch')], max_length=30)),
                ('setup_required', models.BooleanField(default=True)),
                ('cleanup_required', models.BooleanField(default=True)),
                ('equipment_required', models.BooleanField(default=False)),
                ('tableware_required', models.BooleanField(default=False)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('quoted', 'Quote Prepared'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='events.customer')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='events.eventtype')),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='events.servicearea')),
            ],
        ),
    ]
